linter_vhdl:
  description: "VHDL linter: disable VHDL-LS needs restart VSCode."
  type: select
  options:
    disabled: "Disabled"
    ghdl: "GHDL"
    modelsim: "Modelsim"
    xvhdl: "Vivado (xvhdl)"
    none: "VHDL-LS"
  value: "disabled"

llinter_verilog:
  description: "Verilog/SV linter:"
  type: select
  options:
    disabled: "Disabled"
    icarus: "Icarus"
    modelsim: "Modelsim"
    verilator: "Verilator"
    xvlog: "Vivado (xvlog)"
  value: "disabled"

lstyle_verilog:
  description: "Verilog/SV style checker:"
  type: select
  options:
    verible: "Verible"
    disabled: "Disabled"
  value: "disabled"

lstyle_vhdl:
  description: "VHDL style checker:"
  type: select
  options:
    vsg: "VSG"
    disabled: "Disabled"
  value: "disabled"
