############################################
# General
############################################
general:
  title: General
  description:
  general: ./configs/general.yml

############################################
# Documentation
############################################
documentation:
  title: Documentation settings
  description:
  general: ./configs/documentation.yml

############################################
# Editor
############################################
editor:
  title: Editor
  description:
  general: ./configs/editor.yml

############################################
# Formatter
############################################
formatter:
  title: Formatter settings
  description:
  general: ./configs/formatter/general.yml
  secondary:
    istyle:
      title: Verilog/SV iStyle formatter
      description: ""
      page: ./configs/formatter/istyle.yml

    s3sv:
      title: Verilog/SV S3SV formatter
      description: ""
      page: ./configs/formatter/s3sv.yml

    verible:
      title: Verilog/SV Verible formatter
      description: ""
      page: ./configs/formatter/verible.yml

    standalone:
      title: VHDL standalone formatter
      description:
      page: ./configs/formatter/standalone.yml

    svg:
      title: VHDL VSG formatter
      description: "VHDL Style Guide. Analyzes VHDL files for style guide violations."
      page: ./configs/formatter/vsg.yml

############################################
# Linter
############################################
linter:
  title: Linters settings
  description:
  general: ./configs/linter.yml

############################################
# Schematic
############################################
schematic:
  title: Schematic viewer
  description:
  general: ./configs/schematic.yml

############################################
# Templates
############################################
templates:
  title: Templates
  description:
  general: ./configs/templates.yml

############################################
# Tools
############################################
tools:
  title: Formatter settings
  description:
  general: ./configs/tools/general.yml
  secondary:
    ascenlint:
      title: ascenlint
      description: "Ascent Lint performs static source code analysis on HDL code and checks for common coding errors or coding style violations."
      page: ./configs/tools/ascentlint.yml

    cocotb:
      title: Cocotb
      description: ""
      page: ./configs/tools/cocotb.yml

    diamond:
      title: Diamond
      description: "Backend for Lattice Diamond."
      page: ./configs/tools/diamond.yml

    ghdl:
      title: GHDL
      description: "GHDL is an open source VHDL simulator, which fully supports IEEE 1076-1987, IEEE 1076-1993, IEE 1076-2002 and partially the 1076-2008 version of VHDL."
      page: ./configs/tools/ghdl.yml

    icarus:
      title: Icarus
      description: "Icarus Verilog is a Verilog simulation and synthesis tool. It operates as a compiler, compiling source code written in Verilog (IEEE-1364) into some target format."
      page: ./configs/tools/icarus.yml

    icestorm:
      title: Icestorm
      description: "Open source toolchain for Lattice iCE40 FPGAs. Uses yosys for synthesis and arachne-pnr or nextpnr for Place & Route."
      page: ./configs/tools/icestorm.yml

    ise:
      title: ISE
      description: "Xilinx ISE Design Suite."
      page: ./configs/tools/ise.yml

    isem:
      title: ISIM
      description: "Xilinx ISim simulator from ISE design suite."
      page: ./configs/tools/isim.yml

    modelsim:
      title: ModelSim
      description: "ModelSim simulator from Mentor Graphics."
      page: ./configs/tools/modelsim.yml

    morty:
      title: Morty
      description: "Run the (System-) Verilog pickle tool called morty."
      page: ./configs/tools/morty.yml

    quartus:
      itle: Quartus
      description: "The Quartus backend supports Intel Quartus Std and Pro editions to build systems and program the FPGA."
      page: ./configs/tools/quartus.yml

    radiant:
      title: Radiant
      description: "Backend for Lattice Radiant."
      page: ./configs/tools/radiant.yml

    rivierapro:
      title: Rivierapro
      description: "Riviera Pro simulator from Aldec."
      page: ./configs/tools/rivierapro.yml

    siliconcompiler:
      title: SiliconCompiler
      description: 'SiliconCompiler is an open source compiler framework that automates translation from source code to silicon. Check the project documentation: <a href="https://docs.siliconcompiler.com/en/latest/">https://docs.siliconcompiler.com/en/latest/</a>'
      page: ./configs/tools/siliconcompiler.yml

    spyglass:
      title: Spyglass
      description: "Synopsys (formerly Atrenta) Spyglass Backend. Spyglass performs static source code analysis on HDL code and checks for common coding errors or coding style violations."
      page: ./configs/tools/spyglass.yml

    symbiyosys:
      title: SymbiYosys
      description: "SymbiYosys formal verification wrapper for Yosys."
      page: ./configs/tools/symbiyosys.yml

    symbiflow:
      title: Symbiflow
      description: "VHDL Style Guide. Analyzes VHDL files for style guide violations."
      page: ./configs/tools/symbiflow.yml

    trellis:
      title: Trellis
      description: "Project Trellis enables a fully open-source flow for ECP5 FPGAs using Yosys for Verilog synthesis and nextpnr for place and route."
      page: ./configs/tools/trellis.yml

    vcs:
      title: VCS
      description: "Synopsys VCS Backend"
      page: ./configs/tools/vcs.yml

    veriblelint:
      title: VeribleLint
      description: "Verible lint backend (verible-verilog-lint)."
      page: ./configs/tools/veriblelint.yml

    verilator:
      title: Verilator
      description: "Verible lint backend (verible-verilog-lint)."
      page: ./configs/tools/verilator.yml

    vivado:
      title: Vivado
      description: "The Vivado backend executes Xilinx Vivado to build systems and program the FPGA."
      page: ./configs/tools/vivado.yml

    vunit:
      title: VUnit
      description: "VUnit testing framework."
      page: ./configs/tools/vunit.yml

    xcelium:
      title: Xcelium
      description: "Xcelium simulator from Cadence Design Systems."
      page: ./configs/tools/xcelium.yml

    xsim:
      title: XSIM
      description: "XSim simulator from the Xilinx Vivado suite."
      page: ./configs/tools/xsim.yml

    yosys:
      title: Yosys
      description: "Open source synthesis tool targeting many different FPGAs."
      page: ./configs/tools/yosys.yml
